<?php
session_start();
include "php/connect_to_db.php";
include "php/account/user_handeling.php";

$_SESSION['no_of_texts'] = 0;
?>

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="css/index.css">
    <link rel="icon" type="image/svg" href="images/logo.svg"> <!--generated by DALL-E from OpenAI-->
    <title>Wiki</title>
</head>
<body id="parchment">
<div id="header">
    <img src="images/logo.svg" alt="logo" class="logo">
    <div id="text">
        <div id="user_function">
            <?php
            if (isset($_SESSION['valid']) and $_SESSION['valid']) {     //user is logged in
                echo "<a href='php/account/logout.php'  class='button'>Log Out</a></br>";
                echo "<a href='php/account/user.php' class='button'>My Profile</a></br>";
                echo "<a href='php/article/new.php' class='button'>New Article</a>";
            } else {                                                //user isn't logged in
                echo "<a href='register.php' class='button'>Sign Up</a><br><a href='login.php'  class='button'>Sign In</a>";
            }
            ?>
        </div>
        <h1>Wiki</h1>
    </div>
</div>
<hr>
<form action="php/input_check.php" method="post" class="search">
    <label>
        <input name="searchbar" maxlength="20" placeholder="Search Article" type="search">
    </label>
</form>

<table title="Recent Articles">
    <tr>
        <th>Title</th>
        <th>Creator</th>
        <th>Edit Date</th>
    </tr>

    <?php
    $articles = access_db("
SELECT a.Title,`Edit Time`, Name, author.AuthorID, t.ArticleID
From article as a
 INNER JOIN author on a.Creator = author.AuthorID
INNER JOIN text t on a.ArticleID = t.ArticleID
union
SELECT a2.Title,`Edit Time`, author.Name,author.AuthorID, i.ArticleID
FROM article as a2
         INNER JOIN author on a2.Creator = author.AuthorID
         INNER JOIN image i on a2.ArticleID = i.ArticleID

where a2.ArticleID > 0

group by Title
order by `Edit Time` desc
    ");
    if ($articles->num_rows > 0) {
        while ($entry = $articles->fetch_assoc()) {
            $name = access_db("SELECT Name from author where AuthorID={$entry['AuthorID']}")->fetch_array()[0];
            echo "<tr>";
            echo "<td><a href='php/article/show.php?article={$entry['ArticleID']}'  class='table_link'>{$entry['Title']}</a></td>";
            echo "<td>$name</td>";
            echo "<td>{$entry['Edit Time']}</td>";
            echo "</tr>";
        }
    }

    ?>
</body>
</html>